/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "player-list": () => import("@/views/_builtin/player-list/index.vue"),
  business_project: () => import("@/views/business/project/index.vue"),
  business_schema: () => import("@/views/business/schema/index.vue"),
  dashboard_hgs: () => import("@/views/dashboard/hgs/index.vue"),
  dashboard_overall: () => import("@/views/dashboard/overall/index.vue"),
  dashboard_qgs: () => import("@/views/dashboard/qgs/index.vue"),
  hgs_list: () => import("@/views/hgs/list/index.vue"),
  hgs_order: () => import("@/views/hgs/order/index.vue"),
  hgs_statistics: () => import("@/views/hgs/statistics/index.vue"),
  home: () => import("@/views/home/index.vue"),
  qgs_list: () => import("@/views/qgs/list/index.vue"),
  qgs_statistics: () => import("@/views/qgs/statistics/index.vue"),
  qgs_submit: () => import("@/views/qgs/submit/index.vue"),
  system_about: () => import("@/views/system/about/index.vue"),
  system_log: () => import("@/views/system/log/index.vue"),
  system_menu: () => import("@/views/system/menu/index.vue"),
  system_profile: () => import("@/views/system/profile/index.vue"),
  system_role: () => import("@/views/system/role/index.vue"),
  system_user: () => import("@/views/system/user/index.vue"),
};
